const CCLine = {
    name: "Circle Line",
    code: "CC",
    stations: [
        {name: "Dhoby Ghaut", code: "CC1"},
        {name: "Bras Basah", code: "CC2"},
        {name: "Esplanade", code: "CC3"},
        {name: "Promenade", code: "CC4"},
        {name: "Nicoll Highway", code: "CC5"},
        {name: "Stadium", code: "CC6"},
        {name: "Mountbatten", code: "CC7"},
        {name: "Dakota", code: "CC8"},
        {name: "Paya Lebar", code: "CC9"},
        {name: "MacPherson", code: "CC10"},
        {name: "Tai Seng", code: "CC11"},
        {name: "Bartley", code: "CC12"},
        {name: "Serangoon", code: "CC13"},
        {name: "Lorong Chuan", code: "CC14"},
        {name: "Bishan", code: "CC15"},
        {name: "Marymount", code: "CC16"},
        {name: "Caldecott", code: "CC17"},
        {name: "Botanic Gardens", code: "CC19"},
        {name: "Farrer Road", code: "CC20"},
        {name: "Holland Village", code: "CC21"},
        {name: "Buona Vista", code: "CC22"},
        {name: "one-north", code: "CC23"},
        {name: "Kent Ridge", code: "CC24"},
        {name: "Haw Par Villa", code: "CC25"},
        {name: "Pasir Panjang", code: "CC26"},
        {name: "Labrador Park", code: "CC27"},
        {name: "Telok Blangah", code: "CC28"},
        {name: "HarbourFront", code: "CC29"}
    ]
};

const CILine = {
    name: "Cross Island Line",
    code: "CR",
    stations: [
        {name: "Aviation Park", code: "CR1"},
        {name: "Loyang", code: "CR2"},
        {name: "Pasir Ris East", code: "CR3"},
        {name: "Tampines North", code: "CR4"},
        {name: "Defu", code: "CR5"},
        {name: "Hougang", code: "CR6"},
        {name: "Serangoon North", code: "CR7"},
        {name: "Tavistock", code: "CR8"},
        {name: "Ang Mo Kio", code: "CR9"},
        {name: "Teck Ghee", code: "CR10"},
        {name: "Bright Hill", code: "CR11"},
        {name: "Upper Thomson", code: "CR12"},
        {name: "Caldecott", code: "CR13"},
        {name: "Adam", code: "CR14"},
        {name: "Mount Pleasant", code: "CR15"},
        {name: "Stevens", code: "CR16"},
        {name: "Napier", code: "CR17"},
        {name: "Orchard Boulevard", code: "CR18"},
        {name: "Orchard", code: "CR19"},
        {name: "Great World", code: "CR20"},
        {name: "Fort Canning", code: "CR21"},
        {name: "Keppel", code: "CR22"},
        {name: "Cantonment", code: "CR23"},
        {name: "Prince Edward Road", code: "CR24"},
        {name: "Bayshore", code: "CR25"},
        {name: "Siglap", code: "CR26"},
        {name: "Marine Parade", code: "CR27"},
        {name: "Marina East", code: "CR28"},
        {name: "Marina South", code: "CR29"},
        {name: "Gardens by the Bay", code: "CR30"},
        {name: "Founders' Memorial", code: "CR31"},
        {name: "Tanjong Rhu", code: "CR32"},
        {name: "Katong Park", code: "CR33"},
        {name: "Amber", code: "CR34"},
        {name: "Marine Terrace", code: "CR35"},
        {name: "Siglap", code: "CR36"},
        {name: "Bayshore", code: "CR37"},
        {name: "Bedok South", code: "CR38"},
        {name: "Sungei Bedok", code: "CR39"},
        {name: "Xilin", code: "CR40"},
        {name: "Tampines Industrial", code: "CR41"},
        {name: "Pasir Ris", code: "CR42"}
    ]
};

const DTLine = {
    name: "Downtown Line",
    code: "DT",
    stations: [
        {name: "Bukit Panjang", code: "DT1"},
        {name: "Cashew", code: "DT2"},
        {name: "Hillview", code: "DT3"},
        {name: "Hume", code: "DT5"},
        {name: "Beauty World", code: "DT5"},
        {name: "King Albert Park", code: "DT6"},
        {name: "Sixth Avenue", code: "DT7"},
        {name: "Tan Kah Kee", code: "DT8"},
        {name: "Botanic Gardens", code: "DT9"},
        {name: "Stevens", code: "DT10"},
        {name: "Newton", code: "DT11"},
        {name: "Little India", code: "DT12"},
        {name: "Rochor", code: "DT13"},
        {name: "Bugis", code: "DT14"},
        {name: "Promenade", code: "DT15"},
        {name: "Bayfront", code: "DT16"},
        {name: "Downtown", code: "DT17"},
        {name: "Telok Ayer", code: "DT18"},
        {name: "Chinatown", code: "DT19"},
        {name: "Fort Canning", code: "DT20"},
        {name: "Bencoolen", code: "DT21"},
        {name: "Jalan Besar", code: "DT22"},
        {name: "Bendemeer", code: "DT23"},
        {name: "Geylang Bahru", code: "DT24"},
        {name: "Mattar", code: "DT25"},
        {name: "MacPherson", code: "DT26"},
        {name: "Ubi", code: "DT27"},
        {name: "Kaki Bukit", code: "DT28"},
        {name: "Bedok North", code: "DT29"},
        {name: "Bedok Reservoir", code: "DT30"},
        {name: "Tampines West", code: "DT31"},
        {name: "Tampines", code: "DT32"},
        {name: "Tampines East", code: "DT33"},
        {name: "Upper Changi", code: "DT34"}
    ]
};

const EWLine = {
    name: "East West Line",
    code: "EW",
    stations: [
        {name: "Pasir Ris", code: "EW1"},
        {name: "Tampines", code: "EW2"},
        {name: "Simei", code: "EW3"},
        {name: "Tanah Merah", code: "EW4"},
        {name: "Bedok", code: "EW5"},
        {name: "Kembangan", code: "EW6"},
        {name: "Eunos", code: "EW7"},
        {name: "Paya Lebar", code: "EW8"},
        {name: "Aljunied", code: "EW9"},
        {name: "Kallang", code: "EW10"},
        {name: "Lavender", code: "EW11"},
        {name: "Bugis", code: "EW12"},
        {name: "City Hall", code: "EW13"},
        {name: "Raffles Place", code: "EW14"},
        {name: "Tanjong Pagar", code: "EW15"},
        {name: "Outram Park", code: "EW16"},
        {name: "Tiong Bahru", code: "EW17"},
        {name: "Redhill", code: "EW18"},
        {name: "Queenstown", code: "EW19"},
        {name: "Commonwealth", code: "EW20"},
        {name: "Buona Vista", code: "EW21"},
        {name: "Dover", code: "EW22"},
        {name: "Clementi", code: "EW23"},
        {name: "Jurong East", code: "EW24"},
        {name: "Chinese Garden", code: "EW25"},
        {name: "Lakeside", code: "EW26"},
        {name: "Boon Lay", code: "EW27"},
        {name: "Pioneer", code: "EW28"},
        {name: "Joo Koon", code: "EW29"},
        {name: "Gul Circle", code: "EW30"},
        {name: "Tuas Crescent", code: "EW31"},
        {name: "Tuas West Road", code: "EW32"},
        {name: "Tuas Link", code: "EW33"}
    ]
};

const JRLine = {
    name: "Jurong Region Line",
    code: "JS",
    stations: [
        {name: "Choa Chu Kang West", code: "JS1"},
        {name: "Choa Chu Kang", code: "JS2"},
        {name: "Tengah", code: "JS3"},
        {name: "Hong Kah", code: "JS4"},
        {name: "Tawas", code: "JS5"},
        {name: "Nanyang Gateway", code: "JS6"},
        {name: "Nanyang Crescent", code: "JS7"},
        {name: "Enterprise", code: "JS8"},
        {name: "Tukang", code: "JS9"},
        {name: "Jurong Hill", code: "JS10"},
        {name: "Jurong Pier", code: "JS11"},
        {name: "Peng Kang Hill", code: "JS12"},
        {name: "Bahar Junction", code: "JS13"},
        {name: "Gek Poh", code: "JS14"},
        {name: "Tawas", code: "JS15"},
        {name: "NTU", code: "JS16"}
    ]
};

const NELine = {
    name: "North East Line",
    code: "NE",
    stations: [
        {name: "HarbourFront", code: "NE1"},
        {name: "Outram Park", code: "NE3"},
        {name: "Chinatown", code: "NE4"},
        {name: "Clarke Quay", code: "NE5"},
        {name: "Dhoby Ghaut", code: "NE6"},
        {name: "Little India", code: "NE7"},
        {name: "Farrer Park", code: "NE8"},
        {name: "Boon Keng", code: "NE9"},
        {name: "Potong Pasir", code: "NE10"},
        {name: "Woodleigh", code: "NE11"},
        {name: "Serangoon", code: "NE12"},
        {name: "Kovan", code: "NE13"},
        {name: "Hougang", code: "NE14"},
        {name: "Buangkok", code: "NE15"},
        {name: "Sengkang", code: "NE16"},
        {name: "Punggol", code: "NE17"}
    ]
};

const NSLine = {
    name: "North South Line",
    code: "NS",
    stations: [
        {name: "Jurong East", code: "NS1"},
        {name: "Bukit Batok", code: "NS2"},
        {name: "Bukit Gombak", code: "NS3"},
        {name: "Choa Chu Kang", code: "NS4"},
        {name: "Yew Tee", code: "NS5"},
        {name: "Kranji", code: "NS7"},
        {name: "Marsiling", code: "NS8"},
        {name: "Woodlands", code: "NS9"},
        {name: "Admiralty", code: "NS10"},
        {name: "Sembawang", code: "NS11"},
        {name: "Canberra", code: "NS12"},
        {name: "Yishun", code: "NS13"},
        {name: "Khatib", code: "NS14"},
        {name: "Yio Chu Kang", code: "NS15"},
        {name: "Ang Mo Kio", code: "NS16"},
        {name: "Bishan", code: "NS17"},
        {name: "Braddell", code: "NS18"},
        {name: "Toa Payoh", code: "NS19"},
        {name: "Novena", code: "NS20"},
        {name: "Newton", code: "NS21"},
        {name: "Orchard", code: "NS22"},
        {name: "Somerset", code: "NS23"},
        {name: "Dhoby Ghaut", code: "NS24"},
        {name: "City Hall", code: "NS25"},
        {name: "Raffles Place", code: "NS26"},
        {name: "Marina Bay", code: "NS27"},
        {name: "Marina South Pier", code: "NS28"}
    ]
};

const TELine = {
    name: "Thomson-East Coast Line",
    code: "TE",
    stations: [
        {name: "Woodlands North", code: "TE1"},
        {name: "Woodlands", code: "TE2"},
        {name: "Woodlands South", code: "TE3"},
        {name: "Springleaf", code: "TE4"},
        {name: "Lentor", code: "TE5"},
        {name: "Mayflower", code: "TE6"},
        {name: "Bright Hill", code: "TE7"},
        {name: "Upper Thomson", code: "TE8"},
        {name: "Caldecott", code: "TE9"},
        {name: "Mount Pleasant", code: "TE10"},
        {name: "Stevens", code: "TE11"},
        {name: "Napier", code: "TE12"},
        {name: "Orchard Boulevard", code: "TE13"},
        {name: "Orchard", code: "TE14"},
        {name: "Great World", code: "TE15"},
        {name: "Havelock", code: "TE16"},
        {name: "Outram Park", code: "TE17"},
        {name: "Maxwell", code: "TE18"},
        {name: "Shenton Way", code: "TE19"},
        {name: "Marina Bay", code: "TE20"},
        {name: "Marina South", code: "TE21"},
        {name: "Gardens by the Bay", code: "TE22"},
        {name: "Tanjong Rhu", code: "TE23"},
        {name: "Katong Park", code: "TE24"},
        {name: "Tanjong Katong", code: "TE25"},
        {name: "Marine Parade", code: "TE26"},
        {name: "Siglap", code: "TE27"},
        {name: "Bayshore", code: "TE28"},
        {name: "Bedok South", code: "TE29"},
        {name: "Sunrise Way", code: "TE30"},
        {name: "Upper East Coast", code: "TE31"},
        {name: "East Coast", code: "TE32"},
        {name: "Marine Terrace", code: "TE33"},
        {name: "Siglap", code: "TE34"},
        {name: "Bayshore", code: "TE35"},
        {name: "Bedok South", code: "TE36"},
        {name: "Sungei Bedok", code: "TE37"}
    ]
};

// define an array of all the imported files
const mrtStations = [
    EWLine, NSLine, NELine, CCLine, DTLine, TELine, JRLine, CILine
];

// export the array
export default mrtStations;
