const TELine = {
    name: "Thomson-East Coast Line",
    code: "TE",
    stations: [
        {name: "Woodlands North", code: "TE1"},
        {name: "Woodlands", code: "TE2"},
        {name: "Woodlands South", code: "TE3"},
        {name: "Springleaf", code: "TE4"},
        {name: "Lentor", code: "TE5"},
        {name: "Mayflower", code: "TE6"},
        {name: "Bright Hill", code: "TE7"},
        {name: "Upper Thomson", code: "TE8"},
        {name: "Caldecott", code: "TE9"},
        {name: "Mount Pleasant", code: "TE10"},
        {name: "Stevens", code: "TE11"},
        {name: "Napier", code: "TE12"},
        {name: "Orchard Boulevard", code: "TE13"},
        {name: "Orchard", code: "TE14"},
        {name: "Great World", code: "TE15"},
        {name: "Havelock", code: "TE16"},
        {name: "Outram Park", code: "TE17"},
        {name: "Maxwell", code: "TE18"},
        {name: "Shenton Way", code: "TE19"},
        {name: "Marina Bay", code: "TE20"},
        {name: "Marina South", code: "TE21"},
        {name: "Gardens by the Bay", code: "TE22"},
        {name: "Tanjong Rhu", code: "TE23"},
        {name: "Katong Park", code: "TE24"},
        {name: "Tanjong Katong", code: "TE25"},
        {name: "Marine Parade", code: "TE26"},
        {name: "Siglap", code: "TE27"},
        {name: "Bayshore", code: "TE28"},
        {name: "Bedok South", code: "TE29"},
        {name: "Sunrise Way", code: "TE30"},
        {name: "Upper East Coast", code: "TE31"},
        {name: "East Coast", code: "TE32"},
        {name: "Marine Terrace", code: "TE33"},
        {name: "Siglap", code: "TE34"},
        {name: "Bayshore", code: "TE35"},
        {name: "Bedok South", code: "TE36"},
        {name: "Sungei Bedok", code: "TE37"}
    ]
};

module.exports = TELine;
