const CILine = {
    name: "Cross Island Line",
    code: "CR",
    stations: [
        {name: "Aviation Park", code: "CR1"},
        {name: "Loyang", code: "CR2"},
        {name: "Pasir Ris East", code: "CR3"},
        {name: "Tampines North", code: "CR4"},
        {name: "Defu", code: "CR5"},
        {name: "Hougang", code: "CR6"},
        {name: "Serangoon North", code: "CR7"},
        {name: "Tavistock", code: "CR8"},
        {name: "Ang Mo Kio", code: "CR9"},
        {name: "Teck Ghee", code: "CR10"},
        {name: "Bright Hill", code: "CR11"},
        {name: "Upper Thomson", code: "CR12"},
        {name: "Caldecott", code: "CR13"},
        {name: "Adam", code: "CR14"},
        {name: "Mount Pleasant", code: "CR15"},
        {name: "Stevens", code: "CR16"},
        {name: "Napier", code: "CR17"},
        {name: "Orchard Boulevard", code: "CR18"},
        {name: "Orchard", code: "CR19"},
        {name: "Great World", code: "CR20"},
        {name: "Fort Canning", code: "CR21"},
        {name: "Keppel", code: "CR22"},
        {name: "Cantonment", code: "CR23"},
        {name: "Prince Edward Road", code: "CR24"},
        {name: "Bayshore", code: "CR25"},
        {name: "Siglap", code: "CR26"},
        {name: "Marine Parade", code: "CR27"},
        {name: "Marina East", code: "CR28"},
        {name: "Marina South", code: "CR29"},
        {name: "Gardens by the Bay", code: "CR30"},
        {name: "Founders' Memorial", code: "CR31"},
        {name: "Tanjong Rhu", code: "CR32"},
        {name: "Katong Park", code: "CR33"},
        {name: "Amber", code: "CR34"},
        {name: "Marine Terrace", code: "CR35"},
        {name: "Siglap", code: "CR36"},
        {name: "Bayshore", code: "CR37"},
        {name: "Bedok South", code: "CR38"},
        {name: "Sungei Bedok", code: "CR39"},
        {name: "Xilin", code: "CR40"},
        {name: "Tampines Industrial", code: "CR41"},
        {name: "Pasir Ris", code: "CR42"}
    ]
};

module.exports = CILine;
